version: "3"
services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql_pokemon
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-pokemonDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    ports:
      - 3306:3306

    command: --default-authentication-plugin=mysql_native_password